### PR TITLE
Change error handling

### PR DESCRIPTION
**Pull request by lewiscowper**
This improves user experience as the program will now throw at a useful point, rather than logging a message that may be lost in logging churn.

### CODE REVIEW

**Comment by lewiscowper** [comment]
We should squash these commits into the first one. Apologies for the spam

**Comment by joshuaquek** [comment]
hmm I personally feel that we can just just do:

```javascript
...
...
}catch(error){
  throw error
}
```

If we want to stick with `unknownError`, we should should name it as `UnknownError`, to follow proper error type naming conventions. 

Or we could create a class that extends Error and use it in the code:

```javascript
class UnknownError extends Error {
  constructor (message) {
    super()
    this.name = this.constructor.name
    this.message = `Something went wrong during ${message}`
  }
}
```

What do you think? 

However, I can merge your code in for now, because it still beats the previous `console.log(error)` that I wrote, which was an unacceptable mistake on my part hahaha

**Comment by lewiscowper** [comment]
I like the rename to capitalise, but not the class, tbh.

**Comment by joshuaquek** [comment]
Cool, ok I'll do the caps before doing a release. Thanks man!

**Pull request merged**
